/*ADD A DATA ROW (DH3T SMS CHANNEL) TO TABLE T_SM_CHANNEL*/
INSERT INTO T_SM_CHANNEL (NO, NAME, MONTH_NUMBER, MONTH_MAXNUMBER, STATUS, CREATE_TIME, MODIFY_TIME, OPERATOR) VALUES('DH3T','大汉三通','0','300000','0',NOW(),NOW(),'SYSTEM');
