/*修改表字段长度*/
ALTER TABLE T_SM_MARKET MODIFY RET_MSG  VARCHAR (1000) CHARACTER SET utf8mb4 COMMENT '响应报文';
ALTER TABLE T_SM_MARKET_HIS MODIFY RET_MSG  VARCHAR (1000) CHARACTER SET utf8mb4 COMMENT '响应报文';
ALTER TABLE T_SM_NOTIFY MODIFY RET_MSG  VARCHAR (1000) CHARACTER SET utf8mb4 COMMENT '响应报文';
ALTER TABLE T_SM_NOTIFY_HIS MODIFY RET_MSG  VARCHAR (1000) CHARACTER SET utf8mb4 COMMENT '响应报文';
ALTER TABLE T_SM_VERIFYCODE MODIFY RET_MSG  VARCHAR (1000) CHARACTER SET utf8mb4 COMMENT '响应报文';
ALTER TABLE T_SM_VERIFYCODE_HIS MODIFY RET_MSG  VARCHAR (1000) CHARACTER SET utf8mb4 COMMENT '响应报文';
