CREATE TABLE T_MSG_DEVICE (
  ID INT(12) NOT NULL AUTO_INCREMENT COMMENT 'id',
  CELLPHONE_NUM VARCHAR(12) NOT NULL COMMENT '手机号',
  DEVICE_ID VARCHAR(100) NOT NULL COMMENT '设备令牌',
  DEVICE_TYPE CHAR(1) NOT NULL COMMENT '设备类型:1 Andriod 2 IOS',
  CREATE_TIME DATETIME NULL COMMENT '创建时间',
  MODIFY_TIME DATETIME NULL COMMENT '修改时间',
  OPERATOR VARCHAR(50) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID)
);

CREATE TABLE T_MSG_BATCH (
  ID INT(12) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  BATCH_NO VARCHAR(50)  NOT NULL COMMENT '批次号',
  PUSH_TIME DATETIME NOT NULL COMMENT '推送时间',
  IS_INSTANT CHAR(1)  NOT NULL COMMENT '是否立即推送:0,不立即，1：立即',
  IS_ALLPUSH CHAR(1) DEFAULT NULL COMMENT '是否全员推送',
  PUSH_NUM INT(12) DEFAULT NULL COMMENT '推送数',
  SUCCEED_NUM INT(12) DEFAULT NULL COMMENT '下发数',
  ARRIVER_NUM INT(12) DEFAULT NULL COMMENT '到达数',
  EXPAND_NUM INT(12) DEFAULT NULL COMMENT '展开数',
  CLICK_NUM INT(12) DEFAULT NULL COMMENT '点击数',
  INFORM_TITLE VARCHAR(100) DEFAULT NULL COMMENT '通知栏题目',
  INFORM_CONTENT VARCHAR(500)  DEFAULT NULL COMMENT '通知栏内容',
  TRANS_MISSION_CONTENT VARCHAR(500)  DEFAULT NULL COMMENT '透传内容',
  CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
  MODIFY_TIME DATETIME NOT NULL COMMENT '修改时间',
  OPERATOR VARCHAR(50)  DEFAULT NULL COMMENT '创建者',
  PRIMARY KEY (ID)
);

CREATE TABLE T_MSG_PHONE (
  ID INT(12) NOT NULL AUTO_INCREMENT COMMENT 'id',
  CELLPHONE_NUM VARCHAR(12) NOT NULL COMMENT '手机号',
  DEVICE_ID VARCHAR(100) DEFAULT NULL COMMENT '设备号',
  BATCH_NO VARCHAR(50) DEFAULT NULL COMMENT '批次号',
  TASK_ID VARCHAR(50) DEFAULT NULL COMMENT '任务号',
  DEVICE_TYPE CHAR(1) NOT NULL COMMENT '设备类型:1 Andriod 2 IOS',
  PUSH_TIME DATETIME DEFAULT NULL COMMENT '推送时间',
  STATUS VARCHAR(30) DEFAULT NULL COMMENT '状态',
  RET_MSG VARCHAR(100) DEFAULT NULL COMMENT '返回报文',
  CREATE_TIME DATETIME DEFAULT NULL COMMENT '创建时间',
  MODIFY_TIME DATETIME DEFAULT NULL COMMENT '修改时间',
  OPERATOR VARCHAR(30) DEFAULT NULL COMMENT '操作者',
  PRIMARY KEY (ID)
);

CREATE TABLE T_MSG_TASK (
  ID INT(12) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  TASK_ID VARCHAR(50)  NOT NULL COMMENT '任务号',
  BATCH_NO VARCHAR(50) NOT NULL COMMENT '批次号',
  GETUI_NO VARCHAR(50) NOT NULL COMMENT '个推号',
  IS_INSTANT CHAR(1)  NOT NULL COMMENT '是否立即推送:0,不立即，1：立即',
  IS_ALLPUSH CHAR(1) DEFAULT NULL COMMENT '是否全员推送',
  INFORM_TITLE VARCHAR(100) DEFAULT NULL COMMENT '通知栏题目',
  INFORM_CONTENT VARCHAR(500)  DEFAULT NULL COMMENT '通知栏内容',
  SUCCEED_NUM INT(12) DEFAULT NULL COMMENT '下发数',
  ARRIVER_NUM INT(12) DEFAULT NULL COMMENT '到达数',
  EXPAND_NUM INT(12) DEFAULT NULL COMMENT '展开数',
  CLICK_NUM INT(12) DEFAULT NULL COMMENT '点击数',
  PUSH_NUM INT(12) DEFAULT NULL COMMENT '推送数',
  STATUS VARCHAR(2)  DEFAULT NULL COMMENT '状态',
  RET_CODE VARCHAR(60) DEFAULT NULL COMMENT '返回码',
  DEVICE_TYPE CHAR(1)  NOT NULL COMMENT '设备类型:1 Andriod 2 IOS,全员推送为0',
  PUSH_TIME DATETIME NOT NULL COMMENT '推送时间',
  PUSH_BEGIN_TIME DATETIME NOT NULL COMMENT '推送开始时间',
  PUSH_FINISH_TIME DATETIME NOT NULL COMMENT '推送结束时间',
  BACK_RESULT TEXT  COMMENT '返回报文',
  CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
  MODIFY_TIME DATETIME NOT NULL COMMENT '修改时间',
  OPERATOR VARCHAR(50) DEFAULT NULL COMMENT '创建者',
  PRIMARY KEY (ID)
);
