
CREATE TABLE T_SM_CHANNEL (
  ID int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  NO varchar(12) NOT NULL COMMENT '编号',
  NAME varchar(50) NOT NULL COMMENT '名称',
  MONTH_NUMBER int(11) NOT NULL DEFAULT '0' COMMENT '当月发送数量',
  MONTH_MAXNUMBER int(11) NOT NULL DEFAULT '0' COMMENT '每月最大可发送数量',
  STATUS tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态 0停用1启用',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_NO (NO)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信通道表';

CREATE TABLE T_SM_MARKET (
  ID int(11) NOT NULL AUTO_INCREMENT,
  BATCH_NO varchar(50) NOT NULL COMMENT '批次号',
  MOBILE varchar(12) NOT NULL COMMENT '手机号',
  IS_INSTANT tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否立即发送 0否1是',
  SEND_TIME datetime NOT NULL COMMENT '发送时间',
  SEND_MSG varchar(500) NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态' COMMENT '9未发送 0发送中 1成功 2失败',
  RET_MSG varchar(100) DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) COMMENT '发送通道',
  SEND_SM_TYPE tinyint(2) NOT NULL COMMENT '发送短信的类型',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='营销短信表';

CREATE TABLE T_SM_MARKET_HIS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  BATCH_NO varchar(50) NOT NULL COMMENT '批次号',
  MOBILE varchar(12) NOT NULL COMMENT '手机号',
  IS_INSTANT tinyint(1) DEFAULT '0' COMMENT '是否立即发送',
  SEND_TIME datetime NOT NULL COMMENT '发送时间',
  SEND_MSG varchar(500) NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态' COMMENT '9未发送 0发送中 1成功 2失败',
  RET_MSG varchar(100) DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) COMMENT '发送通道',
  SEND_SM_TYPE tinyint(2) NOT NULL COMMENT '发送短信的类型',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='营销短信历史表';

CREATE TABLE T_SM_NOTIFY (
  ID int(11) NOT NULL AUTO_INCREMENT,
  MOBILE varchar(12) NOT NULL COMMENT '手机号',
  SEND_MSG varchar(500) NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态' COMMENT '9未发送 0发送中 1成功 2失败',
  RET_MSG varchar(100) DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) COMMENT '发送通道',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通知短信表';

CREATE TABLE T_SM_NOTIFY_HIS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  MOBILE varchar(12) NOT NULL COMMENT '手机号',
  SEND_MSG varchar(500) NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态' COMMENT '9未发送 0发送中 1成功 2失败',
  RET_MSG varchar(100) DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) COMMENT '发送通道',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通知短信历史表';

CREATE TABLE T_SM_VERIFYCODE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  MOBILE varchar(12) NOT NULL COMMENT '手机号',
  VERIFY_CODE varchar(10) NOT NULL COMMENT '验证码',
  SEND_MSG varchar(100) NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态' COMMENT '9未发送 0发送中 1成功 2失败',
  RET_MSG varchar(100) DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) COMMENT '发送通道',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='验证码短信表';

CREATE TABLE T_SM_VERIFYCODE_HIS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  MOBILE varchar(12) NOT NULL COMMENT '手机号',
  VERIFY_CODE varchar(10) NOT NULL COMMENT '验证码',
  SEND_MSG varchar(100) NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态' COMMENT '9未发送 0发送中 1成功 2失败',
  RET_MSG varchar(100) DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) COMMENT '发送通道',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='验证码短信历史表';

CREATE TABLE T_SM_STATIS (
  ID int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  SM_CHANNEL_TYPE tinyint(1) NOT NULL COMMENT '通道',
  MONTH varchar(6) DEFAULT NULL COMMENT '月份',
  DAY varchar(2) DEFAULT NULL COMMENT '日',
  SEND_NUM int(11) DEFAULT '0' COMMENT '当日发送数量',
  SEND_SUCCEED_NUM int(11) DEFAULT '0' COMMENT '当日发送成功数量',
  SEND_FAILED_NUM int(11) DEFAULT '0' COMMENT '当日发送失败数量',
  REMARK varchar(50) DEFAULT NULL COMMENT '备注',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_STATIS_TIME (MONTH,DAY,CREATE_TIME)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='短信统计表';
