
/*Table structure for table T_SM_CHANNEL */

DROP TABLE IF EXISTS T_SM_CHANNEL;

CREATE TABLE T_SM_CHANNEL (
  ID int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  NO varchar(12) CHARACTER SET utf8mb4 NOT NULL COMMENT '编号',
  NAME varchar(50) CHARACTER SET utf8mb4 NOT NULL COMMENT '名称',
  MONTH_NUMBER int(11) NOT NULL DEFAULT '0' COMMENT '当月发送数量',
  MONTH_MAXNUMBER int(11) NOT NULL DEFAULT '0' COMMENT '每月最大可发送数量',
  STATUS tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态 0停用1启用',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_NO (NO)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='短信通道表';

/*Table structure for table T_SM_MARKET */

DROP TABLE IF EXISTS T_SM_MARKET;

CREATE TABLE T_SM_MARKET (
  ID int(11) NOT NULL AUTO_INCREMENT,
  BATCH_NO varchar(50) CHARACTER SET utf8mb4 NOT NULL COMMENT '批次号',
  MOBILE varchar(12) CHARACTER SET utf8mb4 NOT NULL COMMENT '手机号',
  IS_INSTANT tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否立即发送 0否1是',
  SEND_TIME datetime NOT NULL COMMENT '发送时间',
  SEND_MSG varchar(500) CHARACTER SET utf8mb4 NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态9未发送 0发送中 1成功 2失败',
  RET_MSG varchar(1000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '发送通道0BST 5创蓝',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '操作人',
  SEND_SM_TYPE tinyint(2) NOT NULL COMMENT '发送短信的类型',
  SM_SOURCE varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '来源LCB捞财宝 ONLINE电商',
  PRIMARY KEY (ID),
  KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='短信表';

/*Table structure for table T_SM_MARKET_HIS */

DROP TABLE IF EXISTS T_SM_MARKET_HIS;

CREATE TABLE T_SM_MARKET_HIS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  BATCH_NO varchar(50) CHARACTER SET utf8mb4 NOT NULL COMMENT '批次号',
  MOBILE varchar(12) CHARACTER SET utf8mb4 NOT NULL COMMENT '手机号',
  IS_INSTANT tinyint(1) DEFAULT '0' COMMENT '是否立即发送 0否1是',
  SEND_TIME datetime NOT NULL COMMENT '发送时间',
  SEND_MSG varchar(500) CHARACTER SET utf8mb4 NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '0' COMMENT '发送状态',
  RET_MSG varchar(1000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) DEFAULT NULL COMMENT '发送通道',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '操作人',
  SEND_SM_TYPE tinyint(2) NOT NULL COMMENT '发送短信的类型',
  SM_SOURCE varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='短信历史表';

/*Table structure for table T_SM_NOTIFY */

DROP TABLE IF EXISTS T_SM_NOTIFY;

CREATE TABLE T_SM_NOTIFY (
  ID int(11) NOT NULL AUTO_INCREMENT,
  MOBILE varchar(12) CHARACTER SET utf8mb4 NOT NULL COMMENT '手机号',
  SEND_MSG varchar(500) CHARACTER SET utf8mb4 NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态',
  RET_MSG varchar(1000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) DEFAULT NULL COMMENT '发送通道',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '操作人',
  SM_SOURCE varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='通知短信表';

/*Table structure for table T_SM_NOTIFY_HIS */

DROP TABLE IF EXISTS T_SM_NOTIFY_HIS;

CREATE TABLE T_SM_NOTIFY_HIS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  MOBILE varchar(12) CHARACTER SET utf8mb4 NOT NULL COMMENT '手机号',
  SEND_MSG varchar(500) CHARACTER SET utf8mb4 NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态',
  RET_MSG varchar(1000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) DEFAULT '1' COMMENT '发送通道',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '操作人',
  SM_SOURCE varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='通知短信表';

/*Table structure for table T_SM_STATIS */

DROP TABLE IF EXISTS T_SM_STATIS;

CREATE TABLE T_SM_STATIS (
  ID int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
  SM_CHANNEL_TYPE tinyint(1) NOT NULL COMMENT '通道',
  MONTH varchar(6) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '月份',
  DAY varchar(2) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '日',
  SEND_NUM int(11) DEFAULT '0' COMMENT '当日发送数量',
  SEND_SUCCEED_NUM int(11) DEFAULT '0' COMMENT '当日发送成功数量',
  SEND_FAILED_NUM int(11) DEFAULT '0' COMMENT '当日发送失败数量',
  REMARK varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '备注',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (ID),
  KEY INDEX_STATIS_TIME (MONTH,DAY,CREATE_TIME)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='短信统计表';

/*Table structure for table T_SM_VERIFYCODE */

DROP TABLE IF EXISTS T_SM_VERIFYCODE;

CREATE TABLE T_SM_VERIFYCODE (
  ID int(11) NOT NULL AUTO_INCREMENT,
  MOBILE varchar(12) CHARACTER SET utf8mb4 NOT NULL COMMENT '手机号',
  VERIFY_CODE varchar(10) CHARACTER SET utf8mb4 NOT NULL COMMENT '验证码',
  SEND_MSG varchar(500) CHARACTER SET utf8mb4 NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态',
  RET_MSG varchar(1000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) DEFAULT NULL COMMENT '发送通道',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '操作人',
  SM_SOURCE varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='验证码表';

/*Table structure for table T_SM_VERIFYCODE_HIS */

DROP TABLE IF EXISTS T_SM_VERIFYCODE_HIS;

CREATE TABLE T_SM_VERIFYCODE_HIS (
  ID int(11) NOT NULL AUTO_INCREMENT,
  MOBILE varchar(12) CHARACTER SET utf8mb4 NOT NULL COMMENT '手机号',
  VERIFY_CODE varchar(10) CHARACTER SET utf8mb4 NOT NULL COMMENT '验证码',
  SEND_MSG varchar(500) CHARACTER SET utf8mb4 NOT NULL COMMENT '发送内容',
  SEND_STATUS tinyint(1) DEFAULT '9' COMMENT '发送状态',
  RET_MSG varchar(1000) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '响应报文',
  SM_CHANNEL_TYPE tinyint(1) DEFAULT NULL COMMENT '发送通道',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) CHARACTER SET utf8mb4 DEFAULT NULL COMMENT '操作人',
  SM_SOURCE varchar(20) CHARACTER SET utf8mb4 DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY INDEX_MOBILE_CREATE_TIME (MOBILE,CREATE_TIME)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COMMENT='验证码历史表';

/*data for table t_sm_channel*/
insert into T_SM_CHANNEL (NO, NAME, MONTH_NUMBER, MONTH_MAXNUMBER, STATUS, CREATE_TIME, MODIFY_TIME, OPERATOR) values('253','创蓝','0','550000','1',now(),now(),'system');
insert into T_SM_CHANNEL (NO, NAME, MONTH_NUMBER, MONTH_MAXNUMBER, STATUS, CREATE_TIME, MODIFY_TIME, OPERATOR) values('BST','博士通','0','80000','0',now(),now(),'system');

