CREATE TABLE T_MSG_BATCH (
  ID int(12) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  BATCH_NO varchar(50) NOT NULL COMMENT '批次号',
  PUSH_TIME datetime NOT NULL COMMENT '推送时间',
  PUSH_NUM int(12) DEFAULT NULL COMMENT '推送数',
  SUCCEED_NUM int(12) DEFAULT NULL COMMENT '下发数',
  ARRIVER_NUM int(12) DEFAULT NULL COMMENT '到达数',
  CLICK_NUM int(12) DEFAULT NULL COMMENT '点击数',
  TITLE varchar(100) DEFAULT NULL COMMENT '通知栏题目',
  CONTENT varchar(500) DEFAULT NULL COMMENT '通知栏内容',
  DATA varchar(500) DEFAULT NULL COMMENT '透传内容',
  IS_INSTANT tinyint(1) DEFAULT 0  COMMENT '是否立即推送:0,不立即，1：立即',
  IS_ALLPUSH tinyint(1) DEFAULT 0  COMMENT '是否全员推送:0否1是',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '创建者',
  SERIAL_NO varchar(50) DEFAULT NULL COMMENT '商户发送流水号',
  PRIMARY KEY (ID),
  UNIQUE KEY BATCH_NO (BATCH_NO),
  UNIQUE KEY SERIAL_NO (SERIAL_NO),
  KEY INDEX_CREATE_TIME (CREATE_TIME),
  KEY INDEX_PUSH_TIME (PUSH_TIME)
) ;


CREATE TABLE T_MSG_DEVICE (
  ID int(12) NOT NULL AUTO_INCREMENT COMMENT 'id',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '操作人',
  CELLPHONE_NUM varchar(12)  NOT NULL COMMENT '手机号',
  DEVICE_ID varchar(100)  NOT NULL COMMENT '设备令牌',
  DEVICE_TYPE char(1)  NOT NULL COMMENT '设备类型:1 Andriod 2 IOS',
  PRIMARY KEY (ID),
  UNIQUE KEY CELLPHONE_NUM (CELLPHONE_NUM),
  KEY INDEX_CREATE_TIME (CREATE_TIME)
) ;

CREATE TABLE T_MSG_PHONE (
  ID int(12) NOT NULL AUTO_INCREMENT COMMENT 'id',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(30) DEFAULT NULL COMMENT '操作者',
  CELLPHONE_NUM varchar(12) NOT NULL COMMENT '手机号',
  DEVICE_ID varchar(100) DEFAULT NULL COMMENT '设备号',
  DEVICE_TYPE char(1) DEFAULT NULL COMMENT '设备类型',
  BATCH_NO varchar(50) DEFAULT NULL COMMENT '批次号',
  TASK_NO varchar(50) DEFAULT NULL COMMENT '任务号',
  PUSH_TIME datetime DEFAULT NULL COMMENT '推送时间',
  STATUS varchar(30) DEFAULT NULL COMMENT '状态',
  RET_MSG varchar(100) DEFAULT NULL COMMENT '返回报文',
  PRIMARY KEY (ID),
  KEY INDEX_PUSH_TIME (PUSH_TIME)
) ;


CREATE TABLE T_MSG_TASK (
  ID int(12) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  TASK_NO varchar(50) NOT NULL COMMENT '任务号',
  BATCH_NO varchar(50) NOT NULL COMMENT '批次号',
  SUCCEED_NUM int(12) DEFAULT NULL COMMENT '下发数',
  ARRIVER_NUM int(12) DEFAULT NULL COMMENT '到达数',
  CLICK_NUM int(12) DEFAULT NULL COMMENT '点击数',
  STATUS char(1) DEFAULT NULL COMMENT '状态 9待推送1推送成功2推送失败0推送处理中3统计完成',
  RET_MSG varchar(60)  DEFAULT NULL COMMENT '返回信息',
  RET_DATA varchar(500) DEFAULT NULL COMMENT '返回报文',
  DEVICE_TYPE char(1) NOT NULL COMMENT '设备类型:1 Andriod 2 IOS,全员推送为0',
  PUSH_TIME datetime NOT NULL COMMENT '推送时间',
  IS_INSTANT tinyint(1) DEFAULT 0 COMMENT '是否立即推送:0,不立即，1：立即',
  IS_ALLPUSH tinyint(1) DEFAULT 0 COMMENT '是否全员推送 0否1是',
  THIRD_TASK_NO varchar(50)  DEFAULT NULL COMMENT '个推任务号',
  PUSH_NUM int(12) DEFAULT NULL COMMENT '推送数量',
  PUSH_BEGIN_TIME datetime DEFAULT NULL COMMENT '推送开始时间',
  PUSH_FINISH_TIME datetime DEFAULT NULL COMMENT '推送结束时间',
  TITLE varchar(100)  DEFAULT NULL COMMENT '通知栏标题',
  CONTENT varchar(500)  DEFAULT NULL COMMENT '通知栏内容',
  DATA varchar(500) DEFAULT NULL COMMENT '消息内容',
  CREATE_TIME datetime NOT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '创建者',
  PRIMARY KEY (ID),
  UNIQUE KEY TASK_NO (TASK_NO),
  KEY INDEX_CREATE_TIME (CREATE_TIME),
  KEY INDEX_PUSH_TIME (PUSH_TIME)
);

CREATE TABLE T_MSG_MESSAGE (
  ID int(12) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  MERCHANT_SERIAL_NO varchar(50) NOT NULL COMMENT '商户发送流水号',
  USER_NO varchar(50) NOT NULL COMMENT '用户编号',
  USER_ID varchar(50) NOT NULL COMMENT '用户ID',
  USER_NAME varchar(50) DEFAULT NULL COMMENT '用户姓名',
  USER_PHONE varchar(11) NOT NULL COMMENT '用户手机号',
  TITLE varchar(100) DEFAULT NULL COMMENT '标题',
  SUMMARY varchar(500) DEFAULT NULL COMMENT '摘要',
  CONTENT varchar(500) DEFAULT NULL COMMENT '内容',
  TYPE tinyint(1) DEFAULT '1' COMMENT '类型，1：活动；2：公告',
  STATUS tinyint(1) DEFAULT '1' COMMENT '状态：1：未读；2：已读',
  CREATE_TIME datetime DEFAULT NULL COMMENT '创建时间',
  MODIFY_TIME datetime DEFAULT NULL COMMENT '修改时间',
  OPERATOR varchar(50) DEFAULT NULL COMMENT '创建者',
  PRIMARY KEY (ID),
  KEY INDEX_CREATE_TIME (CREATE_TIME),
  KEY INDEX_USER_ID (USER_ID)
)